//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectingProductionDataSystem.GetTransactions.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FORCE_REGIONAL_SETTINGS {
            get {
                return ((bool)(this["FORCE_REGIONAL_SETTINGS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bg-BG")]
        public string CULTURE_INFO {
            get {
                return ((string)(this["CULTURE_INFO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan IDLE_TIMER_TRANSDACTION_DATA {
            get {
                return ((global::System.TimeSpan)(this["IDLE_TIMER_TRANSDACTION_DATA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public global::System.TimeSpan IDLE_TIMER_TRADE_REPORT_DATA {
            get {
                return ((global::System.TimeSpan)(this["IDLE_TIMER_TRADE_REPORT_DATA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public global::System.TimeSpan IDLE_TIMER_ACTIVE_TRANSACTIONS_DATA {
            get {
                return ((global::System.TimeSpan)(this["IDLE_TIMER_ACTIVE_TRANSACTIONS_DATA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("srv-vm-mes-phd.neftochim.bg")]
        public string PHD_HOST {
            get {
                return ((string)(this["PHD_HOST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3150")]
        public int PHD_PORT {
            get {
                return ((int)(this["PHD_PORT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=AutomatedReportingSystem;Persist Securit" +
            "y Info=True;User ID=arsbase;Password=@ut0r3p0rt!")]
        public string AutomatedReportingSystemConnectionString {
            get {
                return ((string)(this["AutomatedReportingSystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=ASO;uid=PHD2CACHE;pwd=synchronize")]
        public string ScaleConnectionString {
            get {
                return ((string)(this["ScaleConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan IDLE_TIMER_PHD_TRANS_DATA {
            get {
                return ((global::System.TimeSpan)(this["IDLE_TIMER_PHD_TRANS_DATA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kosta.Kiryazov@gmail.com")]
        public string SMTP_TO {
            get {
                return ((string)(this["SMTP_TO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CollectingProductionDataSystem@bmsys.eu")]
        public string SMTP_FROM {
            get {
                return ((string)(this["SMTP_FROM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.7.195")]
        public string SMTP_SERVER {
            get {
                return ((string)(this["SMTP_SERVER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYNC_TRADE_REPORT_DATA {
            get {
                return ((bool)(this["SYNC_TRADE_REPORT_DATA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYNC_ACTIVE_TRANSACTIONS {
            get {
                return ((bool)(this["SYNC_ACTIVE_TRANSACTIONS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYNC_TRANSACTIONS {
            get {
                return ((bool)(this["SYNC_TRANSACTIONS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ACTIVE_TRANS_OFFSET_IN_DAYS {
            get {
                return ((int)(this["ACTIVE_TRANS_OFFSET_IN_DAYS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYNC_PRODUCT_REPORT_DATA {
            get {
                return ((bool)(this["SYNC_PRODUCT_REPORT_DATA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public global::System.TimeSpan IDLE_TIMER_PRODUCTION_REPORT_DATA {
            get {
                return ((global::System.TimeSpan)(this["IDLE_TIMER_PRODUCTION_REPORT_DATA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SYNC_ACTIVE_TRANSACTIONS_OFFSET_IN_HOURS {
            get {
                return ((int)(this["SYNC_ACTIVE_TRANSACTIONS_OFFSET_IN_HOURS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYNC_TRANSACTIONS_BY_PRODUCTS {
            get {
                return ((bool)(this["SYNC_TRANSACTIONS_BY_PRODUCTS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int TRANSACTIONS_BY_PRODUCTS_OFFSET_IN_DAYS {
            get {
                return ((int)(this["TRANSACTIONS_BY_PRODUCTS_OFFSET_IN_DAYS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public global::System.TimeSpan IDLE_TIMER_REPORT_TRANSACTIONS_DATA {
            get {
                return ((global::System.TimeSpan)(this["IDLE_TIMER_REPORT_TRANSACTIONS_DATA"]));
            }
        }
    }
}
