// <auto-generated />
namespace CollectingProductionDataSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CreateShifts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateShifts));
        
        string IMigrationMetadata.Id
        {
            get { return "201510120948224_Create Shifts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
