// <auto-generated />
namespace CollectingProductionDataSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class sapi1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sapi1));
        
        string IMigrationMetadata.Id
        {
            get { return "201511122025488_s-api-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
