namespace CollectingProductionDataSystem.Data.Migrations
{
    using CollectingProductionDataSystem.Models.Nomenclatures;
    using System.Data.Entity.Migrations;

    internal class ProductsDataImporter
    {
        internal static void Insert(CollectingDataSystemDbContext context)
        {
            context.ProductTypes.AddOrUpdate(
                new ProductType
                {
                    Name = "Недефиниран",
                    Products =
                    {
                        new Product
                        {
                            Code = -1,
                            Name = "Недефиниран"
                        }
                    }
                },
                new ProductType
                {
                    Name = "Суровина",
                    Products = 
                    {
                        new Product { Code = 1, Name = "Нефт" },
                        new Product { Code = 2, Name = "Мазут за специфична преработка" },
                        new Product { Code = 3, Name = "Природен газ" },
                        new Product { Code = 4, Name = "МТБЕ-внос" },
                        new Product { Code = 5, Name = "Биокомпонент Б-100" },
                        new Product { Code = 6, Name = "Биоетанол (денаториран)" },
                        new Product { Code = 7, Name = "Биоетанол (неденаториран)" },
                        new Product { Code = 8, Name = "Промишлен газьол (чужд, със съдържание на сяра над 0.2%)" },
                        new Product { Code = 9, Name = "Промишлен газьол (чужд-син, със съдържание на сяра над 0.2%)" },
                        new Product { Code = 10	, Name = "Газьол (чужд,със съдържание на сяра до 0.05%)" },
                        new Product { Code = 11	, Name = "Газьол (чужд,със съдържание на сяра от 0.05% до 0.2%)" },
                        new Product { Code = 12	, Name = "Газьол (чужд-син,със съдържание на сяра до 0.05%)" },
                        new Product { Code = 13	, Name = "Газьол (чужд-син,със съдържание на сяра от 0.05% до 0.2%)" },
                        new Product { Code = 14	, Name = "Котелно гориво (чуждо-други смазочни масла и други масла)" },
                        new Product { Code = 15	, Name = "Котелно гориво (чуждо-тежки горива-сяра до 1.0%)" },
                        new Product { Code = 16	, Name = "Котелно гориво (чуждо-тежки горива-сяра от 1.0% до 2.0%)" },
                        new Product { Code = 17	, Name = "Котелно гориво (чуждо-тежки горива-сяра от 2.0% до 2.8%)" },
                        new Product { Code = 18	, Name = "Котелно гориво (чуждо-тежки горива-сяра над 2.8%)" },
                        new Product { Code = 19	, Name = "Промишлен газьол-внос" },
                        new Product { Code = 20	, Name = "Газьол-внос" },
                        new Product { Code = 21	, Name = "Метанол" },
                        new Product { Code = 22	, Name = "Нормален хексан" },
                        new Product { Code = 23	, Name = "Амоняк" },
                        new Product { Code = 24	, Name = "ШМФ (внос)" },
                        new Product { Code = 25	, Name = "Дизелово гориво висока сяра (внос)" },
                        new Product { Code = 26	, Name = "Некондиционни продукти (вход)" },
                        new Product { Code = 27	, Name = "Газов кондензат" },
                        new Product { Code = 28	, Name = "Корабно остатъчно гориво" },
                        new Product { Code = 29	, Name = "Мазут за СП (AR)" },
                        new Product { Code = 30	, Name = "Мазут за СП (БМ)" },
                        new Product { Code = 31	, Name = "Мазут норси" },
                        new Product { Code = 825, Name = "Дизелово гориво Висока Сяра (Внос) - Смесване" },
                        new Product { Code = 827, Name = "Дизелово гориво Висока Сяра (Внос, Син)  - Смесване" },
                    }
                },
                new ProductType
                {
                    Name = "Стоков продукт",
                    Products = 
                    {
                        new Product { Code = 38, Name = "Автомобилен бензин А 92Н" },
                        new Product { Code = 39, Name = "Автомобилен бензин А 92Н-ЕВРО 5" },
                        new Product { Code = 40, Name = "Автомобилен бензин А 95Н-ЕВРО5" },
                        new Product { Code = 41, Name = "Автомобилен бензин А 98Н-ЕВРО5" },
                        new Product { Code = 42, Name = "Автомобилен бензин А95Н (Био-етанол- 2%)" },
                        new Product { Code = 43, Name = "Автомобилен бензин А95Н (Био-етанол- 3%)" },
                        new Product { Code = 44, Name = "Автомобилен бензин А95Н (Био-етанол- 4%)" },
                        new Product { Code = 45, Name = "Автомобилен бензин А95Н (Био-етанол- 5%)" },
                        new Product { Code = 46, Name = "Автомобилен бензин А95Н (Био-етанол- 6%)" },
                        new Product { Code = 47, Name = "Автомобилен бензин А95Н (Био-етанол- 7%)" },
                        new Product { Code = 48, Name = "Автомобилен бензин А95Н (Био-етанол- 8%)" },
                        new Product { Code = 49, Name = "Автомобилен бензин А95Н (Био-етанол- 9%)" },
                        new Product { Code = 50, Name = "Автомобилен бензин А98Н (Био-етанол- 2%)" },
                        new Product { Code = 51, Name = "Автомобилен бензин А98Н (Био-етанол- 3%)" },
                        new Product { Code = 52, Name = "Автомобилен бензин А98Н (Био-етанол- 4%)" },
                        new Product { Code = 53, Name = "Автомобилен бензин А98Н (Био-етанол- 5%)" },
                        new Product { Code = 54, Name = "Автомобилен бензин А98Н (Био-етанол- 6%)" },
                        new Product { Code = 55, Name = "Автомобилен бензин А98Н (Био-етанол- 7%)" },
                        new Product { Code = 56, Name = "Автомобилен бензин А98Н (Био-етанол- 8%)" },
                        new Product { Code = 57, Name = "Автомобилен бензин А98Н (Био-етанол- 9%)" },
                        new Product { Code = 58, Name = "Автомобилен бензин А 95Н-ЕКТО" },
                        new Product { Code = 59, Name = "Автомобилен бензин А 98Н-ЕКТО" },
                        new Product { Code = 60, Name = "Автомобилен бензин А95Н (Био-етанол- 2%) ЕКТО" },
                        new Product { Code = 61, Name = "Автомобилен бензин А95Н (Био-етанол- 3%) ЕКТО" },
                        new Product { Code = 62, Name = "Автомобилен бензин А95Н (Био-етанол- 4%) ЕКТО" },
                        new Product { Code = 63, Name = "Автомобилен бензин А95Н (Био-етанол- 5%) ЕКТО" },
                        new Product { Code = 64, Name = "Автомобилен бензин А95Н (Био-етанол- 6%) ЕКТО" },
                        new Product { Code = 65, Name = "Автомобилен бензин А95Н (Био-етанол- 7%) ЕКТО" },
                        new Product { Code = 66, Name = "Автомобилен бензин А95Н (Био-етанол- 8%) ЕКТО" },
                        new Product { Code = 67, Name = "Автомобилен бензин А95Н (Био-етанол- 9%) ЕКТО" }, 
                        new Product { Code = 68, Name = "Автомобилен бензин А98Н (Био-етанол- 2%) ЕКТО" },
                        new Product { Code = 69, Name = "Автомобилен бензин А98Н (Био-етанол- 3%) ЕКТО" },
                        new Product { Code = 70, Name = "Автомобилен бензин А98Н (Био-етанол- 4%) ЕКТО" },
                        new Product { Code = 71, Name = "Автомобилен бензин А98Н (Био-етанол- 5%) ЕКТО" },
                        new Product { Code = 72, Name = "Автомобилен бензин А98Н (Био-етанол- 6%) ЕКТО" },
                        new Product { Code = 73, Name = "Автомобилен бензин А98Н (Био-етанол- 7%) ЕКТО" },
                        new Product { Code = 74, Name = "Автомобилен бензин А98Н (Био-етанол- 8%) ЕКТО" },
                        new Product { Code = 75, Name = "Автомобилен бензин А98Н (Био-етанол- 9%) ЕКТО" },
                        new Product { Code = 76, Name = "Автомобилен бензин А 93Н" },
                        new Product { Code = 77, Name = "Реформат-стока" },
                        new Product { Code = 78, Name = "Нискооктанов бензин (НОБ) - лек" },
                        new Product { Code = 79, Name = "МТБЕ-стока" },
                        new Product { Code = 80, Name = "Реактивно гориво ДЖЕТ-А1" },
                        new Product { Code = 81, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (лятно)" },
                        new Product { Code = 82, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (лятно,син)" },
                        new Product { Code = 83, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (лятно,червен)" },
                        new Product { Code = 84, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (зимно)" },
                        new Product { Code = 85, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (зимно,син)" },
                        new Product { Code = 86, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (зимно,червен)" },
                        new Product { Code = 87, Name = "Дизелово гориво ( CFPP - 25)" },
                        new Product { Code = 88, Name = "Дизелово гориво ( CP - 16)" },
                        new Product { Code = 89, Name = "Газьол за извънпътна техника - 0,001%S" },
                        new Product { Code = 90, Name = "Газьол за извънпътна техника - 0,001%S (син)" },
                        new Product { Code = 91, Name = "Газьол за извънпътна техника - 0,001%S (червен)" },
                        new Product { Code = 92, Name = "Газьол за извънпътна техника - 0,1%S" },
                        new Product { Code = 93, Name = "Газьол за извънпътна техника - 0,1%S (син)" },
                        new Product { Code = 94, Name = "Газьол за извънпътна техника - 0,1%S (червен)" },
                        new Product { Code = 95, Name = "Гориво за дизелови двигатели B5 (лято)" },
                        new Product { Code = 96, Name = "Гориво за дизелови двигатели B5 (лято;син)" },
                        new Product { Code = 97, Name = "Гориво за дизелови двигатели B5 (лято;червен)" },
                        new Product { Code = 98, Name = "Гориво за дизелови двигатели B5 (зима)" },
                        new Product { Code = 99, Name = "Гориво за дизелови двигатели B5 (зима;син)" },
                        new Product { Code = 100, Name = "Гориво за дизелови двигатели B5 (зима;червен)" },
                        new Product { Code = 101, Name = "Гориво за дизелови двигатели B6 (лято)" },
                        new Product { Code = 102, Name = "Гориво за дизелови двигатели B6 (лято;син)" },
                        new Product { Code = 103, Name = "Гориво за дизелови двигатели B6 (лято;червен)" },
                        new Product { Code = 104, Name = "Гориво за дизелови двигатели B6 (зима)" },
                        new Product { Code = 105, Name = "Гориво за дизелови двигатели B6 (зима;син)" },
                        new Product { Code = 106, Name = "Гориво за дизелови двигатели B6 (зима;червен)" },
                        new Product { Code = 107, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (лятно)-ЕКТО" },
                        new Product { Code = 108, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (лятно,син)-ЕКТО" },
                        new Product { Code = 109, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (лятно,червен)-ЕКТО" },
                        new Product { Code = 110, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (зимно)-ЕКТО" },
                        new Product { Code = 111, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (зимно,син)-ЕКТО" },
                        new Product { Code = 112, Name = "Дизелово гориво-0.001%S - ЕВРО 5 (зимно,червен)-ЕКТО" },
                        new Product { Code = 113, Name = "Дизелово гориво ( CFPP - 25)-ЕКТО" },
                        new Product { Code = 114, Name = "Дизелово гориво ( CP - 16)-ЕКТО" },
                        new Product { Code = 115, Name = "Гориво за дизелови двигатели B5 (лято)-ЕКТО" },
                        new Product { Code = 116, Name = "Гориво за дизелови двигатели B5 (лято;син)-ЕКТО" },
                        new Product { Code = 117, Name = "Гориво за дизелови двигатели B5 (лято;червен)-ЕКТО" },
                        new Product { Code = 118, Name = "Гориво за дизелови двигатели B5 (зима)-ЕКТО" },
                        new Product { Code = 119, Name = "Гориво за дизелови двигатели B5 (зима;син)-ЕКТО" },
                        new Product { Code = 120, Name = "Гориво за дизелови двигатели B5 (зима;червен)-ЕКТО" },
                        new Product { Code = 121, Name = "Гориво за дизелови двигатели B6 (лято)-ЕКТО" },
                        new Product { Code = 122, Name = "Гориво за дизелови двигатели B6 (лято;син)-ЕКТО" },
                        new Product { Code = 123, Name = "Гориво за дизелови двигатели B6 (лято;червен)-ЕКТО" },
                        new Product { Code = 124, Name = "Гориво за дизелови двигатели B6 (зима)-ЕКТО" },
                        new Product { Code = 125, Name = "Гориво за дизелови двигатели B6 (зима;син)-ЕКТО" },
                        new Product { Code = 126, Name = "Гориво за дизелови двигатели B6 (зима;червен)-ЕКТО" },
                        new Product { Code = 127, Name = "Дизелово гориво ДС" },
                        new Product { Code = 128, Name = "Дизелово гориво ДСЗ" },
                        new Product { Code = 129, Name = "Котелно гориво - 2.7%S" },
                        new Product { Code = 130, Name = "Котелно гориво - 1.0 %S" },
                        new Product { Code = 131, Name = "Котелно гориво бункер" },
                        new Product { Code = 132, Name = "Мазут АО ( стока)" },
                        new Product { Code = 133, Name = "Гудрон-стока" },
                        new Product { Code = 134, Name = "Битум нефтен вискозен  БВ >120" },
                        new Product { Code = 135, Name = "Битум за пътни настилки тип 50/70 ( БВ-60)" },
                        new Product { Code = 136, Name = "Битум за пътни настилки тип 70/100 (БВ-90)" },
                        new Product { Code = 137, Name = "ШМФ (износ)" },
                        new Product { Code = 138, Name = "Пропан бутан ( СПБ)" },
                        new Product { Code = 139, Name = "Пропан-бутан (лек)" },
                        new Product { Code = 140, Name = "Пропан-бутан (тежък)" },
                        new Product { Code = 141, Name = "Пропилен ( стока)" },
                        new Product { Code = 142, Name = "Пропан-пропиленова фракция ( стока)" },
                        new Product { Code = 143, Name = "Пропан-технически" },
                        new Product { Code = 144, Name = "Пропан-бутан (чужд)" },
                        new Product { Code = 145, Name = "Бутан (чужд)" },
                        new Product { Code = 146, Name = "Пропан (чужд)" },
                        new Product { Code = 147, Name = "Газова сяра (буци)" },
                        new Product { Code = 148, Name = "Газова сяра ( гранули)" },
                        new Product { Code = 149, Name = "Газова сяра (замърсена)" },
                        new Product { Code = 150, Name = "Горивен газ (стока за ЛЕГБ)" },
                        new Product { Code = 151, Name = "Полиетилен гликол" },
                        new Product { Code = 152, Name = "Моноетилен гликол" },
                        new Product { Code = 153, Name = "Диетилен гликол" },
                        new Product { Code = 154, Name = "Триетилен гликол" },
                        new Product { Code = 155, Name = "Тетраетилен гликол" },
                        new Product { Code = 156, Name = "Моноетанол амин" },
                        new Product { Code = 157, Name = "Диетанол амин" },
                        new Product { Code = 158, Name = "Триетанол амин" },
                        new Product { Code = 159, Name = "Мак-4" },
                        new Product { Code = 160, Name = "Пан-влакна" },
                        new Product { Code = 161, Name = "НЕСТАНДАРТНО ВЛАКНО КАБЕЛ" },
                        new Product { Code = 162, Name = "НЕСТАНДАРТНО ВЛАКНО СМЕС" },
                        new Product { Code = 163, Name = "НЕСТАНДАРТНО ВЛАКНО ЛЕНТА" },
                        new Product { Code = 164, Name = "НЕСТАНДАРТНО ВЛАКНО ЩАПЕЛ" },
                        new Product { Code = 165, Name = "ПАН Л 3,4 М 125 СМЕС А" },
                        new Product { Code = 166, Name = "ПАН ЩББ 3,4/102 А" },
                        new Product { Code = 167, Name = "ПАН ШБМ 2,6/120 А" },
                        new Product { Code = 168, Name = "ПАН ЩБМ 3,4/60 А" },
                        new Product { Code = 169, Name = "ПАН ЩБМ 3,4/80 А" },
                        new Product { Code = 170, Name = "ПАН ЩМ Т СИН 125 3,4/80 А" },
                        new Product { Code = 171, Name = "ПАН ЩМ ЧЕРЕН 144 3,4/60 А" },
                        new Product { Code = 172, Name = "ПАН ЩМ ЧЕРЕН 144 3,4/80 А" },
                        new Product { Code = 173, Name = "ПОЛИПРОПИЛЕН (наличност)" },
                        new Product { Code = 174, Name = "АТАКТЕН ПОЛИПРОПИЛЕН-ХОМОПОЛИМЕР" },
                        new Product { Code = 175, Name = "ПОЛИПРОПИЛЕН - ПОЛИМЕРНИ ШУШУЛКИ" },
                        new Product { Code = 176, Name = "ПОЛИПРОПИЛЕН - СМЕТЕНИ ГР.С МЕХ.ПРИМЕСИ" },
                        new Product { Code = 177, Name = "ПОЛИПРОПИЛЕН - ОТПАДЪК ЧИСТИ ГР.ОТ ЕКСТР" },
                        new Product { Code = 178, Name = "ПОЛИПРОПИЛЕН 6131 ПТ НЕОЦВ. 1К" },
                        new Product { Code = 179, Name = "ПОЛИПРОПИЛЕН 6131 ПТ НЕОЦВ. 2К" },
                        new Product { Code = 180, Name = "ПОЛИПРОПИЛЕН 6231 НЮАНС" },
                        new Product { Code = 181, Name = "ПОЛИПРОПИЛЕН 6231ПТ НЕОЦВ. I К" },
                        new Product { Code = 182, Name = "ПОЛИПРОПИЛЕН 6231ПТ НЕОЦВ. II К" },
                        new Product { Code = 183, Name = "ПОЛИПРОПИЛЕН 6331 НЕОЦ.1К" },
                        new Product { Code = 184, Name = "ПОЛИПРОПИЛЕН 6331 НЕОЦ.2К" },
                        new Product { Code = 185, Name = "ПОЛИПРОПИЛЕН 6331 НЮАНС" },
                        new Product { Code = 186, Name = "ПОЛИПРОПИЛЕН 6431 /М и DHT I K" },
                        new Product { Code = 187, Name = "ПОЛИПРОПИЛЕН 6431 /М II K" },
                        new Product { Code = 188, Name = "ПОЛИПРОПИЛЕН 6431 НЕОЦ.1К" },
                        new Product { Code = 189, Name = "ПОЛИПРОПИЛЕН 6431 НЕОЦ.2К" },
                        new Product { Code = 190, Name = "ПОЛИПРОПИЛЕН 6431 НЮАНС" },
                        new Product { Code = 191, Name = "ПОЛИПРОПИЛЕН 6531 НЕОЦ.1К" },
                        new Product { Code = 192, Name = "ПОЛИПРОПИЛЕН 6531 НЕОЦ.2К" },
                        new Product { Code = 193, Name = "ПОЛИПРОПИЛЕН 6531 НЮАНС" },
                        new Product { Code = 194, Name = "ПОЛИПРОПИЛЕН 6631 НЕОЦ.1К" },
                        new Product { Code = 195, Name = "ПОЛИПРОПИЛЕН 6631 НЕОЦ.2К" },
                        new Product { Code = 196, Name = "ПОЛИПРОПИЛЕН 6631 N" },
                        new Product { Code = 197, Name = "ПОЛИПРОПИЛЕН 6631 НЮАНС" },
                        new Product { Code = 198, Name = "ПОЛИПРОПИЛЕНОВИ АГЛОМЕРАТИ (ПИТИ)" },
                        new Product { Code = 199, Name = "ПОЛИПРОПИЛЕН АТАКТЕН - ПИТИ (БУЦИ)" },
                        new Product { Code = 200, Name = "ПОЛИПРОПИЛЕНОВ ПРАХ - С ПРИМЕСИ" },
                        new Product { Code = 201, Name = "ПОЛИПРОПИЛЕНОВ ПРАХ - ЧИСТ" },
                        new Product { Code = 202, Name = "ПОЛИПРОПИЛЕН АТАКТЕН-ЗАМЪРСЕН" },
                        new Product { Code = 203, Name = "АТАКТЕН ПОЛИПРОПИЛЕН-ХОМО-К" },
                        new Product { Code = 204, Name = "ПОЛИПРОПИЛЕН ПИТИ ЗАМЪРСЕНИ" },
                        new Product { Code = 205, Name = "Полимерен отпадък" },
                        new Product { Code = 206, Name = "Акрилнитрил" },
                        new Product { Code = 207, Name = "Ацетонитрил" },
                        new Product { Code = 208, Name = "ИЗО-БУТАН (СТОКА)" },
                        new Product { Code = 209, Name = "БИТУМИ" },
                        new Product { Code = 210, Name = "ВТЕЧНЕН ГАЗ-210" },
                        new Product { Code = 212, Name = "КОТЕЛНО ГОРИВО-212" },
                        new Product { Code = 213, Name = "КОТЕЛНО ГОРИВО-213" },
                        new Product { Code = 214, Name = "КОТЕЛНО ГОРИВО-214" },
                        new Product { Code = 215, Name = "ГОРИВЕН ГАЗ-215" },
                        new Product { Code = 216, Name = "ГОРИВЕН ГАЗ-216" },
                        new Product { Code = 217, Name = "ГОРИВЕН ГАЗ-217" },
                        new Product { Code = 218, Name = "ГОРИВЕН ГАЗ-218" },
                        new Product { Code = 219, Name = "Котелно гориво (AR) - 2.7%S" },
                        new Product { Code = 220, Name = "Корабно остатъчно гориво(КОГ) ( AR)" },
                        new Product { Code = 221, Name = "Котелно гориво - (AR) - 1.0%S" },
                        new Product { Code = 222, Name = "ШМФ (износ) - (AR)" },
                        new Product { Code = 225, Name = "ПОЛИПРОПИЛЕН-ХОМОПОЛИМЕР 6531(БОПП)" },
                        new Product { Code = 226, Name = "ПОЛИПРОПИЛЕН-ХОМОПОЛИМЕР 6631(БОПП)" },
                        new Product { Code = 227, Name = "ПОЛИПРОПИЛЕН 6731 НЕОЦ.1К" },
                        new Product { Code = 228, Name = "ГАЗОВА СЯРА (ГРАНУЛИ) ТАБЛЕТИРАНА" },
                        new Product { Code = 500, Name = "Автомобилен бензин А95Н - 500" },
                        new Product { Code = 501, Name = "Автомобилен бензин А95Н - 501" },
                        new Product { Code = 502, Name = "Автомобилен бензин А95Н - 502" },
                        new Product { Code = 503, Name = "Автомобилен бензин А95Н - 503" },
                        new Product { Code = 504, Name = "Автомобилен бензин А95Н - 504" },
                        new Product { Code = 505, Name = "Автомобилен бензин А95Н - 505" },
                        new Product { Code = 506, Name = "Автомобилен бензин А95Н - 506" },
                        new Product { Code = 507, Name = "Автомобилен бензин А95Н - 507" },
                        new Product { Code = 508, Name = "Автомобилен бензин А95Н - 508" },
                        new Product { Code = 509, Name = "Автомобилен бензин А95Н - 509" },
                        new Product { Code = 510, Name = "Автомобилен бензин А95Н - 510" },
                        new Product { Code = 511, Name = "Автомобилен бензин А95Н - 511" },
                        new Product { Code = 512, Name = "Автомобилен бензин А95Н - 512" },
                        new Product { Code = 513, Name = "Автомобилен бензин А95Н - 513" },
                        new Product { Code = 514, Name = "Автомобилен бензин А95Н - 514" },
                        new Product { Code = 515, Name = "Автомобилен бензин А95Н - 515" },
                        new Product { Code = 516, Name = "Автомобилен бензин А95Н - 516" },
                        new Product { Code = 517, Name = "Автомобилен бензин А95Н - 517" },
                        new Product { Code = 518, Name = "Автомобилен бензин А95Н - 518" },
                        new Product { Code = 519, Name = "Автомобилен бензин А95Н - 519" },
                        new Product { Code = 520, Name = "Автомобилен бензин А95Н - 520" },
                        new Product { Code = 521, Name = "Автомобилен бензин А95Н - 521" },
                        new Product { Code = 522, Name = "Автомобилен бензин А95Н - 522" },
                        new Product { Code = 523, Name = "Автомобилен бензин А95Н - 523" },
                        new Product { Code = 524, Name = "Автомобилен бензин А95Н - 524" },
                        new Product { Code = 525, Name = "Автомобилен бензин А95Н - 525" },
                        new Product { Code = 526, Name = "Автомобилен бензин А95Н - 526" },
                        new Product { Code = 527, Name = "Автомобилен бензин А95Н - 527" },
                        new Product { Code = 528, Name = "Автомобилен бензин А95Н - 528" },
                        new Product { Code = 529, Name = "Автомобилен бензин А95Н - 529" },
                        new Product { Code = 530, Name = "Автомобилен бензин А95Н - 530" },
                        new Product { Code = 531, Name = "Автомобилен бензин А95Н - 531" },
                        new Product { Code = 532, Name = "Автомобилен бензин А95Н - 532" },
                        new Product { Code = 533, Name = "Гориво за дизелови двигатели - 533" },
                        new Product { Code = 534, Name = "Гориво за дизелови двигатели - 534" },
                        new Product { Code = 535, Name = "Гориво за дизелови двигатели - 535" },
                        new Product { Code = 536, Name = "Гориво за дизелови двигатели - 536" },
                        new Product { Code = 537, Name = "Гориво за дизелови двигатели - 537" },
                        new Product { Code = 538, Name = "Гориво за дизелови двигатели - 538" },
                        new Product { Code = 539, Name = "Гориво за дизелови двигатели - 539" },
                        new Product { Code = 540, Name = "Гориво за дизелови двигатели - 540" },
                        new Product { Code = 541, Name = "Гориво за дизелови двигатели - 541" },
                        new Product { Code = 542, Name = "Гориво за дизелови двигатели - 542" },
                        new Product { Code = 543, Name = "Гориво за дизелови двигатели - 543" },
                        new Product { Code = 544, Name = "Гориво за дизелови двигатели - 544" },
                        new Product { Code = 545, Name = "Гориво за дизелови двигатели - 545" },
                        new Product { Code = 546, Name = "Гориво за дизелови двигатели - 546" },
                        new Product { Code = 547, Name = "Гориво за дизелови двигатели - 547" },
                        new Product { Code = 548, Name = "Гориво за дизелови двигатели - 548" },
                        new Product { Code = 549, Name = "Гориво за дизелови двигатели - 549" },
                        new Product { Code = 550, Name = "Гориво за дизелови двигатели - 550" },
                        new Product { Code = 551, Name = "Гориво за дизелови двигатели - 551" },
                        new Product { Code = 552, Name = "Гориво за дизелови двигатели - 552" },
                        new Product { Code = 553, Name = "Гориво за дизелови двигатели - 553" },
                        new Product { Code = 554, Name = "Гориво за дизелови двигатели - 554" },
                        new Product { Code = 555, Name = "Гориво за дизелови двигатели - 555" },
                        new Product { Code = 556, Name = "Гориво за дизелови двигатели - 556" },
                        new Product { Code = 557, Name = "Гориво за дизелови двигатели - 557" },
                        new Product { Code = 558, Name = "Гориво за дизелови двигатели - 558" },
                        new Product { Code = 559, Name = "Гориво за дизелови двигатели - 559" },
                        new Product { Code = 560, Name = "Гориво за дизелови двигатели - 560" },
                        new Product { Code = 561, Name = "Гориво за дизелови двигатели - B6(CP)" },
                        new Product { Code = 562, Name = "Гориво за дизелови двигатели - B6(CP)-EKTO" },
                        new Product { Code = 579, Name = "Нискооктанов бензин (НОБ) - тежък" },
                        new Product { Code = 585, Name = "Автомобилен бензин А94Н" },
                        new Product { Code = 586, Name = "Бензин алкилат (стока)" },
                        new Product { Code = 700, Name = "EC3246A" },
                        new Product { Code = 701, Name = "EC3404A" },
                        new Product { Code = 702, Name = "EC1010B" },
                        new Product { Code = 703, Name = "EC1005A" },
                        new Product { Code = 704, Name = "EC1021B" },
                        new Product { Code = 705, Name = "NALCO 1801" },
                        new Product { Code = 706, Name = "EC3149A" },
                        new Product { Code = 707, Name = "EC2472A" },
                        new Product { Code = 708, Name = "EC2134A" },
                        new Product { Code = 709, Name = "EC1017A" },
                        new Product { Code = 710, Name = "EC9029A" },
                        new Product { Code = 711, Name = "EC9019B" },
                        new Product { Code = 712, Name = "Инхибитор CHIMEC 1044" },
                        new Product { Code = 713, Name = "KURITA AP-2103" },
                        new Product { Code = 714, Name = "KURITA CI 6407" },
                        new Product { Code = 811, Name = "Дизелово гориво-0.001%S - Евро 5 (Лятно) - Смесване" },
                        new Product { Code = 821, Name = "Дизелово гориво-0.001%S - Евро 5 (Лятно, Син)  - Смесване" },
                        new Product { Code = 828, Name = "Корабно Остатъчно Гориво (КОГ) - Смесване" },
                        new Product { Code = 829, Name = "Корабно Остатъчно Гориво (КОГ) (AR) - След Смесване" },
                        new Product { Code = 841, Name = "Дизелово гориво-0.001%S - Евро 5 (Зимно) - Смесване" },
                        new Product { Code = 851, Name = "Дизелово гориво-0.001%S - Евро 5 (Зимно, Син) - Смесване" },
                    }
                },
                new ProductType
                {
                    Name = "Полуфабрикати и компоненти",
                    Products = 
                    {
                        new Product { Code = 231, Name = "Водород (ВИ)" },
                        new Product { Code = 232, Name = "Водород-съдържащ газ (ВСГ)" },
                        new Product { Code = 233, Name = "Въглеводороден газ (ВВГ)" },
                        new Product { Code = 234, Name = "Въглеводороди (леки)" },
                        new Product { Code = 235, Name = "Сух газ" },
                        new Product { Code = 236, Name = "Смесен горивен газ" },
                        new Product { Code = 237, Name = "Пропан бутан (НПБ)" },
                        new Product { Code = 238, Name = "Пропан бутанова фракция" },
                        new Product { Code = 239, Name = "Пропан-пропиленова фракция" },
                        new Product { Code = 240, Name = "Пропилен" },
                        new Product { Code = 241, Name = "Изо-бутан" },
                        new Product { Code = 242, Name = "Бутан-бутиленова фракция (ББФ)" },
                        new Product { Code = 243, Name = "Изо-бутан-бутиленова фракция (изо-ББФ)" },
                        new Product { Code = 244, Name = "Пропан" },
                        new Product { Code = 245, Name = "Нормален бутан" },
                        new Product { Code = 246, Name = "Рафинат II" },
                        new Product { Code = 247, Name = "Рафинат III" },
                        new Product { Code = 248, Name = "Етан-пропанова фракция" },
                        new Product { Code = 249, Name = "Фракция С5" },
                        new Product { Code = 250, Name = "Сяроводород" },
                        new Product { Code = 251, Name = "Сярна киселина" },
                        new Product { Code = 252, Name = "Отработена сярна киселина" },
                        new Product { Code = 253, Name = "Азот (газообразен)" },
                        new Product { Code = 254, Name = "Азот (течен)" },
                        new Product { Code = 255, Name = "Кислород (газообразен)" },
                        new Product { Code = 256, Name = "Кислород (течен)" },
                        new Product { Code = 257, Name = "Бензинова фракция от АД (НК-100)" },
                        new Product { Code = 258, Name = "Бензинова фракция от АД (100-180)" },
                        new Product { Code = 259, Name = "Бензинова фракция от АД" },
                        new Product { Code = 260, Name = "Бензин отгон" },
                        new Product { Code = 261, Name = "Бензин реформат" },
                        new Product { Code = 262, Name = "Бензин алкилат" },
                        new Product { Code = 263, Name = "Крекин бензин" },
                        new Product { Code = 264, Name = "МТБЕ" },
                        new Product { Code = 265, Name = "Хидроочистен бензин (ХО- Ксилоли)" },
                        new Product { Code = 266, Name = "Бензин хидрогенизат  (ХОБ-1)" },
                        new Product { Code = 267, Name = "Пиробензин" },
                        new Product { Code = 268, Name = "Керосинова фракция от АД" },
                        new Product { Code = 269, Name = "Керосинова фракция хидрирана" },
                        new Product { Code = 270, Name = "Дизелова фракция от АД" },
                        new Product { Code = 271, Name = "Дизелова фракция от ВДМ" },
                        new Product { Code = 272, Name = "Дизелова фракция от АВД-1" },
                        new Product { Code = 273, Name = "Дизелова фракция от ТК" },
                        new Product { Code = 274, Name = "Дизелова фракция от С-100" },
                        new Product { Code = 275, Name = "Дизелова фракция" },
                        new Product { Code = 276, Name = "Дизелова фракция хидрирана" },
                        new Product { Code = 277, Name = "Атмосферен газьол" },
                        new Product { Code = 278, Name = "Лек каталитичен газьол" },
                        new Product { Code = 279, Name = "Тежък каталитичен газьол" },
                        new Product { Code = 280, Name = "Мазут от първична дестилация" },
                        new Product { Code = 281, Name = "Широка маслена фракция (ШМФ)" },
                        new Product { Code = 282, Name = "Гудрон" },
                        new Product { Code = 283, Name = "Тежка гудронова фракция за собствени нужди(ТГСН)" },
                        new Product { Code = 284, Name = "Тежък гудрон" },
                        new Product { Code = 285, Name = "Газова сяра-течна" }, 
                        new Product { Code = 286, Name = "КОТЕЛНО ГОРИВО - 1% (СН)" },
                        new Product { Code = 287, Name = "ХИДРООЧИСТЕНА С3-С4 ФРАКЦИЯ (ХО- КСИЛОЛИ)" },
                        new Product { Code = 288, Name = "БУТИЛЕН-ИЗОБУТИЛ.Ф/Я" },
                        new Product { Code = 289, Name = "БУТИЛКИ ПАБ" },
                        new Product { Code = 290, Name = "ГОРГАЗЗАСОБСТВНУЖДИ" },
                        new Product { Code = 291, Name = "ПРОП.ПРОПИЛ.ФР.-ОЧИС" },
                        new Product { Code = 292, Name = "РЕАКТГОРИВОДЖЕТ-А 1" },
                        new Product { Code = 293, Name = "ТЕХНИЧЕСКИ ПРОПАН" },
                    }
                },
                new ProductType
                {
                    Name = "Адитиви",
                    Products = 
                    {
                        new Product { Code = 316, Name = "Уловени нефтопродукти" },
                        new Product { Code = 317, Name = "Нефтени утайки" },
                        new Product { Code = 318, Name = "Отпадък (утайки)" },
                        new Product { Code = 319, Name = "Шлам" },
                        new Product { Code = 320, Name = "Некондиционни продукти" },
                        new Product { Code = 321, Name = "Окислени масла" },
                        new Product { Code = 322, Name = "Отработени масла" },
                        new Product { Code = 323, Name = "Кокс" },
                        new Product { Code = 324, Name = "Незавършена продукция (в инсталациите)" },
                        new Product { Code = 325, Name = "Регенерирано МДЕА" },
                        new Product { Code = 326, Name = "Наситено МДЕА" },
                        new Product { Code = 327, Name = "Свежо МДЕА" },
                        new Product { Code = 328, Name = "Регенерирано МЕА" },
                        new Product { Code = 329, Name = "Наситено МЕА" },
                        new Product { Code = 330, Name = "Свежо МЕА" },
                        new Product { Code = 331, Name = "Некондиционни продукти" },
                        new Product { Code = 332, Name = "Утайки от плцещ" },
                    }
                },
                new ProductType
                {
                    Name = "Смазочни масла за съоръжения",
                    Products = 
                    {
                        new Product { Code = 345, Name = "Масло Shell Tellus 68" },
                        new Product { Code = 346, Name = "Масло Shell Tellus 68 /Tellus S2 M68/" },
                        new Product { Code = 347, Name = "Масло Shell Remula oil X30Gr" },
                        new Product { Code = 348, Name = "Масло АН46" },
                        new Product { Code = 349, Name = "Масло АН68 (И40А)" },
                        new Product { Code = 350, Name = "Масло МХЛ-32 (ИГП18)" },
                        new Product { Code = 351, Name = "Масло МХЛ-68 (ИГП38)" },
                        new Product { Code = 352, Name = "Масло МХЛ-46 (H46A)" },
                        new Product { Code = 353, Name = "Масло МХЛ-150" },
                        new Product { Code = 354, Name = "Масло МВК150 (К150)" },
                        new Product { Code = 355, Name = "Масло МВК220 (К220)" },
                        new Product { Code = 356, Name = "Масло М10Д ( М10Г2к)" },
                        new Product { Code = 357, Name = "Масло РМ68 ( Ролон 68)" },
                        new Product { Code = 358, Name = "Масло РМ68" },
                        new Product { Code = 359, Name = "Масло РМ150" },
                        new Product { Code = 360, Name = "Масло ТП32, (Тп22С и TbA32E)" },
                        new Product { Code = 361, Name = "Масло ТП46 (TbA46E)" },
                        new Product { Code = 362, Name = "Масло 90ЕР (Т90ЕР2)" },
                        new Product { Code = 363, Name = "Масло трансформаторно" },
                        new Product { Code = 364, Name = "Масло Shell Clavus G46" },
                        new Product { Code = 365, Name = "Масло Shell Omala 220" },
                        new Product { Code = 366, Name = "Масло Shell Donax TM" },
                        new Product { Code = 367, Name = "Приста АН460" },
                        new Product { Code = 368, Name = "Shell Helix Ultra 5W40" },
                        new Product { Code = 369, Name = "Mobil DTE oil LIGHT" },
                        new Product { Code = 370, Name = "масло Shell Tellus S 46" },
                        new Product { Code = 371, Name = "Shell Tellus 46 /Tellus S2 M 46/" },
                        new Product { Code = 372, Name = "Масло Турбо дизел 15W40/Rimula  15W40/Лукойл Авангард Ултра 15W40" },
                        new Product { Code = 373, Name = "Масло Shell Vitrea M 150" },
                        new Product { Code = 374, Name = "Shell Turbo T46" },
                        new Product { Code = 375, Name = "Масло Приста АН 15" },
                        new Product { Code = 376, Name = "Масло Shell Termia B /Heat transfer S2/" },
                        new Product { Code = 377, Name = "Масло Royco 782" },
                        new Product { Code = 378, Name = "Масло mobilube GX80W90" },
                        new Product { Code = 379, Name = "Масло редукторно РМ 320" },
                        new Product { Code = 380, Name = "Трансмисионо толина 90" },
                        new Product { Code = 381, Name = "Хидравлично МХЛ - 150" },
                        new Product { Code = 382, Name = "Емулсол 113 Е /Бориол/" },
                        new Product { Code = 383, Name = "ЛТ2Т / Двутактово масло/" },
                        new Product { Code = 384, Name = "adinol turbine oil 46" },
                        new Product { Code = 385, Name = "Енергол АС-С-460" },
                        new Product { Code = 386, Name = "Шел клавус G-32" },
                        new Product { Code = 387, Name = "Шел Клавус G - 68" },
                        new Product { Code = 388, Name = "Шел омала 320" },
                        new Product { Code = 389, Name = "Шел Корена D-68" },
                        new Product { Code = 390, Name = "Шел Турбо Т-32" },
                        new Product { Code = 391, Name = "Shell tellus  S-68" },
                        new Product { Code = 392, Name = "Мобилубе НD 80W90" },
                        new Product { Code = 393, Name = "Mobil DTE 11M" },
                        new Product { Code = 394, Name = "Mobil DTE 25" },
                        new Product { Code = 395, Name = "Масло MOBIL DTE 16 M" },
                        new Product { Code = 396, Name = "Масло MOBIL DTE oil Medium" },
                        new Product { Code = 397, Name = "Масло SHELL TELLUS 100" },
                        new Product { Code = 398, Name = "Масло ENERGOL RC 100" },
                        new Product { Code = 399, Name = "AGIP ACER SDE 15W40" },
                        new Product { Code = 400, Name = "AGIP SMO 20W50" },
                        new Product { Code = 401, Name = "AGIP BLASIA 150" },
                        new Product { Code = 402, Name = "AGIP BLASIA 100" },
                        new Product { Code = 403, Name = "AGIP BLASIA 220" },
                        new Product { Code = 404, Name = "AGIP BLASIA 680" },
                        new Product { Code = 405, Name = "AGIP  BLASIA  68" },
                        new Product { Code = 406, Name = "AGIP OTE 68" },
                        new Product { Code = 407, Name = "AGIP OSO 46" },
                        new Product { Code = 408, Name = "Масло хидравлично Н.Н.719.1025" },
                        new Product { Code = 409, Name = "Масло диелектрично Н.Н. 719.1026" },
                        new Product { Code = 410, Name = "Масло хидравлично Н.Н. 719.1028" },
                        new Product { Code = 411, Name = "Масло диелектрично Н.Н. 719.1029" },
                        new Product { Code = 412, Name = "AGIP OSO 68" },
                        new Product { Code = 413, Name = "AGIP VAS 460" },
                        new Product { Code = 414, Name = "Масло Бреокс 50А1000" },
                        new Product { Code = 415, Name = "Масло Бреокс 1400SP" },
                        new Product { Code = 416, Name = "TURMSILON U3000W" },
                        new Product { Code = 417, Name = "АЕРОШЕЛФЛУИД 4" },
                        new Product { Code = 418, Name = "Масло RARUS SHC 1025" },
                        new Product { Code = 419, Name = "Масло RARUS 426" },
                        new Product { Code = 420, Name = "Масло УНИВЕРСАЛ ЕНДЖИНЕ ОЙЛ 10W30" },
                        new Product { Code = 421, Name = "ШЕЛ ОМАЛА 220HD" },
                        new Product { Code = 422, Name = "Масло Shell Tivela S200" },
                        new Product { Code = 423, Name = "SILTERM 800" },
                        new Product { Code = 424, Name = "GEM-4-100 kluber syntetik" },
                        new Product { Code = 425, Name = "Shell Omala 150" },
                        new Product { Code = 426, Name = "Shell Tivella S220" },
                        new Product { Code = 427, Name = "Масло Aral Vitam P3580" },
                        new Product { Code = 428, Name = "Кофражно масло КМ15" },
                        new Product { Code = 429, Name = "Масло ENERGOL CS 100" },
                        new Product { Code = 430, Name = "Масло-430" },
                        new Product { Code = 431, Name = "Масло-431" },
                        new Product { Code = 432, Name = "Масло-432" },
                        new Product { Code = 433, Name = "Масло-433" },
                        new Product { Code = 434, Name = "Масло-434" },
                        new Product { Code = 435, Name = "Масло-435" },
                        new Product { Code = 436, Name = "SHELL TELUS S3 М100" },
                        new Product { Code = 437, Name = "MOBIL UNIVIS HVI 26" },
                        new Product { Code = 438, Name = "ADVANCE VSX 2 FC HELIX" },
                        new Product { Code = 439, Name = "CASTROL MAGNATES 5W40/ OEST ETA HCS SAE 5W40" },
                    }
                },
                new ProductType
                {
                    Name = "Смазочни масла за влагане в производството",
                    Products = 
                    {
                        new Product { Code = 441, Name = "Масло процесно бяло минерално (Oндина 917 и WOP15)" },
                        new Product { Code = 442, Name = "Процесно масло за ПЕВН Shell Ondina 934" },
                        new Product { Code = 443, Name = "Процесно масло за каучук (Heavy Extract и RPO620N)" },
                        new Product { Code = 444, Name = "Процесно масло за каучук Shell Flavex 595" },
                    }
                },
                new ProductType
                {
                    Name = "Добавки и присадки",
                    Products = 
                    {
                        new Product { Code = 457, Name = "Смазващи присадки за дизелово гориво" },
                        new Product { Code = 458, Name = "Добавки за реактивно и дизелово горива  Стадис 450" },
                        new Product { Code = 459, Name = "Добавки за дизелово гориво  WASA" },
                        new Product { Code = 460, Name = "Депресатори за дизелово гориво" },
                        new Product { Code = 461, Name = "Полифункционална добавка за бензин  Керопур" },
                        new Product { Code = 462, Name = "Биодизел Б100" },
                        new Product { Code = 463, Name = "Биоетанол (денатуриран)" },
                        new Product { Code = 464, Name = "Биоетанол (неденатуриран)" },
                        new Product { Code = 465, Name = "Нормален хексан" },
                        new Product { Code = 466, Name = "Цетанова присадка за дизелово гориво" },
                        new Product { Code = 467, Name = "АГИДОЛ-1" },
                        new Product { Code = 468, Name = "Йонол 75 за JET A-1" },
                        new Product { Code = 469, Name = "Dodigen 481" },
                        new Product { Code = 470, Name = "Маркиращ разтвор(жълт 124+ син 79)-GOM BLUE BU10Y;  HFA72" },
                        new Product { Code = 471, Name = "Маркиращ разтвор(жълт124+ червен19)- GOM RED BU10Y; HFA88" },
                        new Product { Code = 472, Name = "БЕКТО-HITEC 6437 L (за авт. бензини)" },
                        new Product { Code = 473, Name = "ДЕКТО-HITEC 4691 (за диз. горива)" },
                        new Product { Code = 474, Name = "Химикал-редуциращ dP( FLOMX7C-260CAB)" },
                        new Product { Code = 475, Name = "Адитив -7" },
                        new Product { Code = 476, Name = "Адитив -8" },
                        new Product { Code = 477, Name = "Адитив -9" },
                        new Product { Code = 478, Name = "Адитив -10" },
                        new Product { Code = 479, Name = "Адитив -11" },
                        new Product { Code = 480, Name = "Адитив -12" },
                        new Product { Code = 481, Name = "NEMO 6133 (ШЕЛ)" },
                        new Product { Code = 482, Name = "NEMO 2041 (ШЕЛ)" },
                        new Product { Code = 483, Name = "NEMO 2009 А (ШЕЛ)" },
                        new Product { Code = 484, Name = "NEMO 2022 С (ШЕЛ)" },
                        new Product { Code = 485, Name = "NEMO 4010 (ШЕЛ)" },
                        new Product { Code = 486, Name = "NEMO XXXX2 (ШЕЛ)" },
                        new Product { Code = 487, Name = "NEMO XXXX3 (ШЕЛ)" },
                        new Product { Code = 488, Name = "NEMO XXXX4 (ШЕЛ)" },
                        new Product { Code = 489, Name = "NEMO XXXX5 (ШЕЛ)" },
                        new Product { Code = 490, Name = "NEMO XXXX6 (ШЕЛ)" },
                        new Product { Code = 491, Name = "Адитив -1 (БЕКТО)" },
                        new Product { Code = 492, Name = "Адитив -2 (ДЕКТО)" },
                        new Product { Code = 493, Name = "Адитив -3" },
                        new Product { Code = 494, Name = "Адитив -4" },
                        new Product { Code = 495, Name = "Адитив -5" },
                        new Product { Code = 495, Name = "Адитив -6" },
                        new Product { Code = 497, Name = "Адитив -13" },
                        new Product { Code = 498, Name = "Адитив -14" },
                        new Product { Code = 499, Name = "Антиокислителна присадка АО-080" },
                        new Product { Code = 901, Name = "ЕКО АС 700 (ДГ)" },
                        new Product { Code = 902, Name = "ЕКО Р 996 (Бензин)" },
                        new Product { Code = 903, Name = "ЕКО Адитив (ДГ)" },
                        new Product { Code = 904, Name = "ЕКО Адитив (Бензин)" },
                        new Product { Code = 910, Name = "ОМV DPP 14 ( ДГ)" },
                        new Product { Code = 911, Name = "ОМV GPP 08 ( Бензин)" },
                        new Product { Code = 912, Name = "OMV Адитив ( ДГ)" },
                        new Product { Code = 913, Name = "OMV Адитив ( Бензин)" },
                    }
                },
                new ProductType
                {
                    Name = "Енергоресурси",
                    Products = { }
                },
                new ProductType
                {
                    Name = "Пари",
                    Products = { }
                },
                new ProductType
                {
                    Name = "Химикали",
                    Products = { }
                },
                new ProductType
                {
                    Name = "Електроенергия",
                    Products = { }
                },
                new ProductType
                {
                    Name = "Преработено",
                    Products = { }
                },
                new ProductType
                {
                    Name = "Произведено",
                    Products = { }
                },
                new ProductType 
                { 
                    Name = "Ремонт",
                    Products = 
                    { 
                        new Product { Code = -2, Name = "В ремонт" },
                        new Product { Code = -3, Name = "В ремонт с вода" },
                        new Product { Code = -4, Name = "Празен" },
                    }
                });

            context.SaveChanges();
        }
    }
}
