//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_GlobalResources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollectingProductionDataSystem.Web.App_GlobalResources.HelpResource", typeof(HelpResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationLog.
        /// </summary>
        public static string ApplicationLog {
            get {
                return ResourceManager.GetString("ApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyData.
        /// </summary>
        public static string DailyData {
            get {
                return ResourceManager.GetString("DailyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyDataEnergyPositions.
        /// </summary>
        public static string DailyDataEnergyPositions {
            get {
                return ResourceManager.GetString("DailyDataEnergyPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyDataExpedition.
        /// </summary>
        public static string DailyDataExpedition {
            get {
                return ResourceManager.GetString("DailyDataExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyDataMeasuringPositions.
        /// </summary>
        public static string DailyDataMeasuringPositions {
            get {
                return ResourceManager.GetString("DailyDataMeasuringPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyDataStatusTank.
        /// </summary>
        public static string DailyDataStatusTank {
            get {
                return ResourceManager.GetString("DailyDataStatusTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyMeasuringPositions.
        /// </summary>
        public static string DailyMeasuringPositions {
            get {
                return ResourceManager.GetString("DailyMeasuringPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnteredByUserValues.
        /// </summary>
        public static string EnteredByUserValues {
            get {
                return ResourceManager.GetString("EnteredByUserValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalMessages.
        /// </summary>
        public static string GlobalMessages {
            get {
                return ResourceManager.GetString("GlobalMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpNomenclature.
        /// </summary>
        public static string HelpNomenclature {
            get {
                return ResourceManager.GetString("HelpNomenclature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpProductionData.
        /// </summary>
        public static string HelpProductionData {
            get {
                return ResourceManager.GetString("HelpProductionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Installation {
            get {
                return ResourceManager.GetString("Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeasuringPositions.
        /// </summary>
        public static string MeasuringPositions {
            get {
                return ResourceManager.GetString("MeasuringPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyAir.
        /// </summary>
        public static string MonthlyAir {
            get {
                return ResourceManager.GetString("MonthlyAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyData.
        /// </summary>
        public static string MonthlyData {
            get {
                return ResourceManager.GetString("MonthlyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyDataChemicalClearWater.
        /// </summary>
        public static string MonthlyDataChemicalClearWater {
            get {
                return ResourceManager.GetString("MonthlyDataChemicalClearWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyDataChemicals.
        /// </summary>
        public static string MonthlyDataChemicals {
            get {
                return ResourceManager.GetString("MonthlyDataChemicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyDataCircularWater.
        /// </summary>
        public static string MonthlyDataCircularWater {
            get {
                return ResourceManager.GetString("MonthlyDataCircularWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyDataElectricalEnergy.
        /// </summary>
        public static string MonthlyDataElectricalEnergy {
            get {
                return ResourceManager.GetString("MonthlyDataElectricalEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyDataFreshWater.
        /// </summary>
        public static string MonthlyDataFreshWater {
            get {
                return ResourceManager.GetString("MonthlyDataFreshWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyDataHeatEnergy.
        /// </summary>
        public static string MonthlyDataHeatEnergy {
            get {
                return ResourceManager.GetString("MonthlyDataHeatEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyDataHydroCarbons.
        /// </summary>
        public static string MonthlyDataHydroCarbons {
            get {
                return ResourceManager.GetString("MonthlyDataHydroCarbons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyDataIndoorPipelines.
        /// </summary>
        public static string MonthlyDataIndoorPipelines {
            get {
                return ResourceManager.GetString("MonthlyDataIndoorPipelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyDataPotableWater.
        /// </summary>
        public static string MonthlyDataPotableWater {
            get {
                return ResourceManager.GetString("MonthlyDataPotableWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyDataTechPlants.
        /// </summary>
        public static string MonthlyDataTechPlants {
            get {
                return ResourceManager.GetString("MonthlyDataTechPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyDataWorkingHours.
        /// </summary>
        public static string MonthlyDataWorkingHours {
            get {
                return ResourceManager.GetString("MonthlyDataWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyFuel.
        /// </summary>
        public static string MonthlyFuel {
            get {
                return ResourceManager.GetString("MonthlyFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthlyNitrogen.
        /// </summary>
        public static string MonthlyNitrogen {
            get {
                return ResourceManager.GetString("MonthlyNitrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomCauseForEdit.
        /// </summary>
        public static string NomCauseForEdit {
            get {
                return ResourceManager.GetString("NomCauseForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomDirection.
        /// </summary>
        public static string NomDirection {
            get {
                return ResourceManager.GetString("NomDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomMeasuringUnit.
        /// </summary>
        public static string NomMeasuringUnit {
            get {
                return ResourceManager.GetString("NomMeasuringUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomPhdServers.
        /// </summary>
        public static string NomPhdServers {
            get {
                return ResourceManager.GetString("NomPhdServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomProduct.
        /// </summary>
        public static string NomProduct {
            get {
                return ResourceManager.GetString("NomProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomShift.
        /// </summary>
        public static string NomShift {
            get {
                return ResourceManager.GetString("NomShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomSortMaterial.
        /// </summary>
        public static string NomSortMaterial {
            get {
                return ResourceManager.GetString("NomSortMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomTypeMaterial.
        /// </summary>
        public static string NomTypeMaterial {
            get {
                return ResourceManager.GetString("NomTypeMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomTypeProduct.
        /// </summary>
        public static string NomTypeProduct {
            get {
                return ResourceManager.GetString("NomTypeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomTypeProductDaily.
        /// </summary>
        public static string NomTypeProductDaily {
            get {
                return ResourceManager.GetString("NomTypeProductDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomTypeProductShift.
        /// </summary>
        public static string NomTypeProductShift {
            get {
                return ResourceManager.GetString("NomTypeProductShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NomTypeTransport.
        /// </summary>
        public static string NomTypeTransport {
            get {
                return ResourceManager.GetString("NomTypeTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanNorm.
        /// </summary>
        public static string PlanNorm {
            get {
                return ResourceManager.GetString("PlanNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string Plant {
            get {
                return ResourceManager.GetString("Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanValuesInstallations.
        /// </summary>
        public static string PlanValuesInstallations {
            get {
                return ResourceManager.GetString("PlanValuesInstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionData.
        /// </summary>
        public static string ProductionData {
            get {
                return ResourceManager.GetString("ProductionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftData.
        /// </summary>
        public static string ShiftData {
            get {
                return ResourceManager.GetString("ShiftData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftDataHighwayPipeLines.
        /// </summary>
        public static string ShiftDataHighwayPipeLines {
            get {
                return ResourceManager.GetString("ShiftDataHighwayPipeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftDataMeasuringPositions.
        /// </summary>
        public static string ShiftDataMeasuringPositions {
            get {
                return ResourceManager.GetString("ShiftDataMeasuringPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftDataMeasuringPositionsReport.
        /// </summary>
        public static string ShiftDataMeasuringPositionsReport {
            get {
                return ResourceManager.GetString("ShiftDataMeasuringPositionsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftDataTank.
        /// </summary>
        public static string ShiftDataTank {
            get {
                return ResourceManager.GetString("ShiftDataTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statatistics.
        /// </summary>
        public static string Statatistics {
            get {
                return ResourceManager.GetString("Statatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryReportData.
        /// </summary>
        public static string SummaryReportData {
            get {
                return ResourceManager.GetString("SummaryReportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryReportDescription.
        /// </summary>
        public static string SummaryReportDescription {
            get {
                return ResourceManager.GetString("SummaryReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamDataFlows.
        /// </summary>
        public static string TeamDataFlows {
            get {
                return ResourceManager.GetString("TeamDataFlows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
