//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_GlobalResources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollectingProductionDataSystem.Web.App_GlobalResources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Loaded.
        /// </summary>
        public static string AutomaticData {
            get {
                return ResourceManager.GetString("AutomaticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Value.
        /// </summary>
        public static string AutomaticValue {
            get {
                return ResourceManager.GetString("AutomaticValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing password of user.
        /// </summary>
        public static string ChangePasswordMessage {
            get {
                return ResourceManager.GetString("ChangePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have change your password successfully!.
        /// </summary>
        public static string ChanhePasswordSuccess {
            get {
                return ResourceManager.GetString("ChanhePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Area....
        /// </summary>
        public static string ChooseArea {
            get {
                return ResourceManager.GetString("ChooseArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Direction.
        /// </summary>
        public static string ChooseDirection {
            get {
                return ResourceManager.GetString("ChooseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose factory....
        /// </summary>
        public static string ChooseFactory {
            get {
                return ResourceManager.GetString("ChooseFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Parks....
        /// </summary>
        public static string ChooseParks {
            get {
                return ResourceManager.GetString("ChooseParks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose process unit....
        /// </summary>
        public static string ChooseProcessUnit {
            get {
                return ResourceManager.GetString("ChooseProcessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Process Units....
        /// </summary>
        public static string ChooseProcessUnits {
            get {
                return ResourceManager.GetString("ChooseProcessUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose production shift....
        /// </summary>
        public static string ChooseProductionShift {
            get {
                return ResourceManager.GetString("ChooseProductionShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Data Mechanism.
        /// </summary>
        public static string CollectingDataMechanism {
            get {
                return ResourceManager.GetString("CollectingDataMechanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Account.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} was created..
        /// </summary>
        public static string CreateUserSuccess {
            get {
                return ResourceManager.GetString("CreateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Data.
        /// </summary>
        public static string DailyData {
            get {
                return ResourceManager.GetString("DailyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desctiption.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason For Edit.
        /// </summary>
        public static string EditReason {
            get {
                return ResourceManager.GetString("EditReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Water Level.
        /// </summary>
        public static string FreeWaterLevel {
            get {
                return ResourceManager.GetString("FreeWaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}!.
        /// </summary>
        public static string GreetingMessage {
            get {
                return ResourceManager.GetString("GreetingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid Level.
        /// </summary>
        public static string LiquidLevel {
            get {
                return ResourceManager.GetString("LiquidLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a Collecting Production Data System account to log in..
        /// </summary>
        public static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Value.
        /// </summary>
        public static string ManualValue {
            get {
                return ResourceManager.GetString("ManualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Unit.
        /// </summary>
        public static string MeasureUnit {
            get {
                return ResourceManager.GetString("MeasureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeasuringPointsData.
        /// </summary>
        public static string MeasuringPointsData {
            get {
                return ResourceManager.GetString("MeasuringPointsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Standard Volume.
        /// </summary>
        public static string NetStandardVolume {
            get {
                return ResourceManager.GetString("NetStandardVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park Name.
        /// </summary>
        public static string ParkName {
            get {
                return ResourceManager.GetString("ParkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parks.
        /// </summary>
        public static string Parks {
            get {
                return ResourceManager.GetString("Parks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Unit.
        /// </summary>
        public static string ProcessUnit {
            get {
                return ResourceManager.GetString("ProcessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Unit Name.
        /// </summary>
        public static string ProcessUnitName {
            get {
                return ResourceManager.GetString("ProcessUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Units.
        /// </summary>
        public static string ProcessUnits {
            get {
                return ResourceManager.GetString("ProcessUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Shift.
        /// </summary>
        public static string ProductionShift {
            get {
                return ResourceManager.GetString("ProductionShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Level.
        /// </summary>
        public static string ProductLevel {
            get {
                return ResourceManager.GetString("ProductLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Timestamp.
        /// </summary>
        public static string RecordTimestamp {
            get {
                return ResourceManager.GetString("RecordTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Density.
        /// </summary>
        public static string ReferenceDensity {
            get {
                return ResourceManager.GetString("ReferenceDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Administration.
        /// </summary>
        public static string RolesAdministration {
            get {
                return ResourceManager.GetString("RolesAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts Data.
        /// </summary>
        public static string ShiftsData {
            get {
                return ResourceManager.GetString("ShiftsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Slect Roles....
        /// </summary>
        public static string SlectRoles {
            get {
                return ResourceManager.GetString("SlectRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Name.
        /// </summary>
        public static string TankName {
            get {
                return ResourceManager.GetString("TankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanks Data.
        /// </summary>
        public static string TanksData {
            get {
                return ResourceManager.GetString("TanksData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        public static string TanksDateSelector {
            get {
                return ResourceManager.GetString("TanksDateSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Park.
        /// </summary>
        public static string TanksParkSelector {
            get {
                return ResourceManager.GetString("TanksParkSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Shift.
        /// </summary>
        public static string TanksShiftMinutesOffsetSelector {
            get {
                return ResourceManager.GetString("TanksShiftMinutesOffsetSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Daily Data.
        /// </summary>
        public static string UnitsDailyData {
            get {
                return ResourceManager.GetString("UnitsDailyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Data.
        /// </summary>
        public static string UnitsData {
            get {
                return ResourceManager.GetString("UnitsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        public static string UnitsDateSelector {
            get {
                return ResourceManager.GetString("UnitsDateSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Unit.
        /// </summary>
        public static string UnitsProcessUnitSelector {
            get {
                return ResourceManager.GetString("UnitsProcessUnitSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Shift.
        /// </summary>
        public static string UnitsProcessUnitShiftSelector {
            get {
                return ResourceManager.GetString("UnitsProcessUnitShiftSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Administration.
        /// </summary>
        public static string UsersAdministration {
            get {
                return ResourceManager.GetString("UsersAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight In Air.
        /// </summary>
        public static string WeightInAir {
            get {
                return ResourceManager.GetString("WeightInAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight In Vacuum.
        /// </summary>
        public static string WeightInVacuum {
            get {
                return ResourceManager.GetString("WeightInVacuum", resourceCulture);
            }
        }
    }
}
