//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_GlobalResources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollectingProductionDataSystem.Web.App_GlobalResources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Excepition &lt;br/&gt;[ton].
        /// </summary>
        public static string ActiveQuantity {
            get {
                return ResourceManager.GetString("ActiveQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateGroup.
        /// </summary>
        public static string AggregateGroup {
            get {
                return ResourceManager.GetString("AggregateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateParameter.
        /// </summary>
        public static string AggregateParameter {
            get {
                return ResourceManager.GetString("AggregateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation Current Level.
        /// </summary>
        public static string AggregationCurrentLevel {
            get {
                return ResourceManager.GetString("AggregationCurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation Formula.
        /// </summary>
        public static string AggregationFormula {
            get {
                return ResourceManager.GetString("AggregationFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation Members.
        /// </summary>
        public static string AggregationMembers {
            get {
                return ResourceManager.GetString("AggregationMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Loaded.
        /// </summary>
        public static string AutomaticData {
            get {
                return ResourceManager.GetString("AutomaticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Value.
        /// </summary>
        public static string AutomaticValue {
            get {
                return ResourceManager.GetString("AutomaticValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvailableRoomHighExtreme.
        /// </summary>
        public static string AvailableRoomHighExtreme {
            get {
                return ResourceManager.GetString("AvailableRoomHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvailableRoomLowExtreme.
        /// </summary>
        public static string AvailableRoomLowExtreme {
            get {
                return ResourceManager.GetString("AvailableRoomLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AverageTemperatureHighExtreme.
        /// </summary>
        public static string AverageTemperatureHighExtreme {
            get {
                return ResourceManager.GetString("AverageTemperatureHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AverageTemperatureLowExtreme.
        /// </summary>
        public static string AverageTemperatureLowExtreme {
            get {
                return ResourceManager.GetString("AverageTemperatureLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Expedition&lt;br/&gt;[ton].
        /// </summary>
        public static string AvtoQuantity {
            get {
                return ResourceManager.GetString("AvtoQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Minutes.
        /// </summary>
        public static string BeginMinutes {
            get {
                return ResourceManager.GetString("BeginMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Time.
        /// </summary>
        public static string BeginTime {
            get {
                return ResourceManager.GetString("BeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Formula.
        /// </summary>
        public static string CalculatedFormula {
            get {
                return ResourceManager.GetString("CalculatedFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing password of user.
        /// </summary>
        public static string ChangePasswordMessage {
            get {
                return ResourceManager.GetString("ChangePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have change your password successfully!.
        /// </summary>
        public static string ChanhePasswordSuccess {
            get {
                return ResourceManager.GetString("ChanhePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Area....
        /// </summary>
        public static string ChooseArea {
            get {
                return ResourceManager.GetString("ChooseArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Direction.
        /// </summary>
        public static string ChooseDirection {
            get {
                return ResourceManager.GetString("ChooseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose factory....
        /// </summary>
        public static string ChooseFactory {
            get {
                return ResourceManager.GetString("ChooseFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Material Type....
        /// </summary>
        public static string ChooseMaterialType {
            get {
                return ResourceManager.GetString("ChooseMaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Measure Unit....
        /// </summary>
        public static string ChooseMeasureUnit {
            get {
                return ResourceManager.GetString("ChooseMeasureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Parks....
        /// </summary>
        public static string ChooseParks {
            get {
                return ResourceManager.GetString("ChooseParks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Plant ....
        /// </summary>
        public static string ChoosePlant {
            get {
                return ResourceManager.GetString("ChoosePlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose process unit....
        /// </summary>
        public static string ChooseProcessUnit {
            get {
                return ResourceManager.GetString("ChooseProcessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Process Units....
        /// </summary>
        public static string ChooseProcessUnits {
            get {
                return ResourceManager.GetString("ChooseProcessUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Product....
        /// </summary>
        public static string ChooseProduct {
            get {
                return ResourceManager.GetString("ChooseProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose production shift....
        /// </summary>
        public static string ChooseProductionShift {
            get {
                return ResourceManager.GetString("ChooseProductionShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Product Type....
        /// </summary>
        public static string ChooseProductType {
            get {
                return ResourceManager.GetString("ChooseProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Data Mechanism.
        /// </summary>
        public static string CollectingDataMechanism {
            get {
                return ResourceManager.GetString("CollectingDataMechanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlPoint.
        /// </summary>
        public static string ControlPoint {
            get {
                return ResourceManager.GetString("ControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorrectionFactor.
        /// </summary>
        public static string CorrectionFactor {
            get {
                return ResourceManager.GetString("CorrectionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Account.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} was created..
        /// </summary>
        public static string CreateUserSuccess {
            get {
                return ResourceManager.GetString("CreateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentInspectionDataTag.
        /// </summary>
        public static string CurrentInspectionDataTag {
            get {
                return ResourceManager.GetString("CurrentInspectionDataTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Data.
        /// </summary>
        public static string DailyData {
            get {
                return ResourceManager.GetString("DailyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Product Type.
        /// </summary>
        public static string DailyProductType {
            get {
                return ResourceManager.GetString("DailyProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyProductType.
        /// </summary>
        public static string DailyProductType1 {
            get {
                return ResourceManager.GetString("DailyProductType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyProductTypes.
        /// </summary>
        public static string DailyProductTypes {
            get {
                return ResourceManager.GetString("DailyProductTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desctiption.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction1 {
            get {
                return ResourceManager.GetString("Direction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string Directions {
            get {
                return ResourceManager.GetString("Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason For Edit.
        /// </summary>
        public static string EditReason {
            get {
                return ResourceManager.GetString("EditReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons For Edit.
        /// </summary>
        public static string EditReasons {
            get {
                return ResourceManager.GetString("EditReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstimatedCompressibilityFactor.
        /// </summary>
        public static string EstimatedCompressibilityFactor {
            get {
                return ResourceManager.GetString("EstimatedCompressibilityFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstimatedDensity.
        /// </summary>
        public static string EstimatedDensity {
            get {
                return ResourceManager.GetString("EstimatedDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstimatedPressure.
        /// </summary>
        public static string EstimatedPressure {
            get {
                return ResourceManager.GetString("EstimatedPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstimatedTemperature.
        /// </summary>
        public static string EstimatedTemperature {
            get {
                return ResourceManager.GetString("EstimatedTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factories.
        /// </summary>
        public static string Factories {
            get {
                return ResourceManager.GetString("Factories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string Factory1 {
            get {
                return ResourceManager.GetString("Factory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Water Level.
        /// </summary>
        public static string FreeWaterLevel {
            get {
                return ResourceManager.GetString("FreeWaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeWaterLevelHighExtreme.
        /// </summary>
        public static string FreeWaterLevelHighExtreme {
            get {
                return ResourceManager.GetString("FreeWaterLevelHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeWaterLevelLowExtreme.
        /// </summary>
        public static string FreeWaterLevelLowExtreme {
            get {
                return ResourceManager.GetString("FreeWaterLevelLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeWaterVolumeHighExtreme.
        /// </summary>
        public static string FreeWaterVolumeHighExtreme {
            get {
                return ResourceManager.GetString("FreeWaterVolumeHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeWaterVolumeLowExtreme.
        /// </summary>
        public static string FreeWaterVolumeLowExtreme {
            get {
                return ResourceManager.GetString("FreeWaterVolumeLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullUserName {
            get {
                return ResourceManager.GetString("FullUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, {0}!.
        /// </summary>
        public static string GreetingMessage {
            get {
                return ResourceManager.GetString("GreetingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrossObservableVolumeHighExtreme.
        /// </summary>
        public static string GrossObservableVolumeHighExtreme {
            get {
                return ResourceManager.GetString("GrossObservableVolumeHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrossObservableVolumeLowExtreme.
        /// </summary>
        public static string GrossObservableVolumeLowExtreme {
            get {
                return ResourceManager.GetString("GrossObservableVolumeLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrossStandardVolumeHighExtreme.
        /// </summary>
        public static string GrossStandardVolumeHighExtreme {
            get {
                return ResourceManager.GetString("GrossStandardVolumeHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrossStandardVolumeLowExtreme.
        /// </summary>
        public static string GrossStandardVolumeLowExtreme {
            get {
                return ResourceManager.GetString("GrossStandardVolumeLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikunk.
        /// </summary>
        public static string Ikunk {
            get {
                return ResourceManager.GetString("Ikunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventories.
        /// </summary>
        public static string Inventories {
            get {
                return ResourceManager.GetString("Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCalculated.
        /// </summary>
        public static string IsCalculated {
            get {
                return ResourceManager.GetString("IsCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEditable.
        /// </summary>
        public static string IsEditable {
            get {
                return ResourceManager.GetString("IsEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEnergy.
        /// </summary>
        public static string IsEnergy {
            get {
                return ResourceManager.GetString("IsEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInspectionPoint.
        /// </summary>
        public static string IsInspectionPoint {
            get {
                return ResourceManager.GetString("IsInspectionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsMaterial.
        /// </summary>
        public static string IsMaterial {
            get {
                return ResourceManager.GetString("IsMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jp Expedition&lt;br/&gt;[ton].
        /// </summary>
        public static string JpQuantity {
            get {
                return ResourceManager.GetString("JpQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid Level.
        /// </summary>
        public static string LiquidLevel {
            get {
                return ResourceManager.GetString("LiquidLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiquidLevelHighExtreme.
        /// </summary>
        public static string LiquidLevelHighExtreme {
            get {
                return ResourceManager.GetString("LiquidLevelHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiquidLevelLowExtreme.
        /// </summary>
        public static string LiquidLevelLowExtreme {
            get {
                return ResourceManager.GetString("LiquidLevelLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a Collecting Production Data System account to log in..
        /// </summary>
        public static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Value.
        /// </summary>
        public static string ManualValue {
            get {
                return ResourceManager.GetString("ManualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaterialType.
        /// </summary>
        public static string MaterialType1 {
            get {
                return ResourceManager.GetString("MaterialType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaterialTypes.
        /// </summary>
        public static string MaterialTypes {
            get {
                return ResourceManager.GetString("MaterialTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaximumFlow.
        /// </summary>
        public static string MaximumCost {
            get {
                return ResourceManager.GetString("MaximumCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxVolumeHighExtreme.
        /// </summary>
        public static string MaxVolumeHighExtreme {
            get {
                return ResourceManager.GetString("MaxVolumeHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxVolumeLowExtreme.
        /// </summary>
        public static string MaxVolumeLowExtreme {
            get {
                return ResourceManager.GetString("MaxVolumeLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeasurementPointsProductsConfig.
        /// </summary>
        public static string MeasurementPointsProductsConfig {
            get {
                return ResourceManager.GetString("MeasurementPointsProductsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeasurementUnits.
        /// </summary>
        public static string MeasurementUnits {
            get {
                return ResourceManager.GetString("MeasurementUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Unit.
        /// </summary>
        public static string MeasureUnit {
            get {
                return ResourceManager.GetString("MeasureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeasureUnit.
        /// </summary>
        public static string MeasureUnit1 {
            get {
                return ResourceManager.GetString("MeasureUnit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeasuringPointConfig.
        /// </summary>
        public static string MeasuringPointConfig {
            get {
                return ResourceManager.GetString("MeasuringPointConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeasuringPointsData.
        /// </summary>
        public static string MeasuringPointsData {
            get {
                return ResourceManager.GetString("MeasuringPointsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Standard Volume.
        /// </summary>
        public static string NetStandardVolume {
            get {
                return ResourceManager.GetString("NetStandardVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetStandardVolumeHighExtreme.
        /// </summary>
        public static string NetStandardVolumeHighExtreme {
            get {
                return ResourceManager.GetString("NetStandardVolumeHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetStandardVolumeLowExtreme.
        /// </summary>
        public static string NetStandardVolumeLowExtreme {
            get {
                return ResourceManager.GetString("NetStandardVolumeLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclatures.
        /// </summary>
        public static string Nomenclatures {
            get {
                return ResourceManager.GetString("Nomenclatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Nomenclature From File.
        /// </summary>
        public static string NomUploadTitle {
            get {
                return ResourceManager.GetString("NomUploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservableDensityHighExtreme.
        /// </summary>
        public static string ObservableDensityHighExtreme {
            get {
                return ResourceManager.GetString("ObservableDensityHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservableDensityLowExtreme.
        /// </summary>
        public static string ObservableDensityLowExtreme {
            get {
                return ResourceManager.GetString("ObservableDensityLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Minutes.
        /// </summary>
        public static string OffsetMinutes {
            get {
                return ResourceManager.GetString("OffsetMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park.
        /// </summary>
        public static string Park {
            get {
                return ResourceManager.GetString("Park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park.
        /// </summary>
        public static string Park1 {
            get {
                return ResourceManager.GetString("Park1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park Name.
        /// </summary>
        public static string ParkName {
            get {
                return ResourceManager.GetString("ParkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parks.
        /// </summary>
        public static string Parks {
            get {
                return ResourceManager.GetString("Parks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentages.
        /// </summary>
        public static string Percentages {
            get {
                return ResourceManager.GetString("Percentages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagAvailableRoom.
        /// </summary>
        public static string PhdTagAvailableRoom {
            get {
                return ResourceManager.GetString("PhdTagAvailableRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagAverageTemperature.
        /// </summary>
        public static string PhdTagAverageTemperature {
            get {
                return ResourceManager.GetString("PhdTagAverageTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagFreeWaterLevel.
        /// </summary>
        public static string PhdTagFreeWaterLevel {
            get {
                return ResourceManager.GetString("PhdTagFreeWaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagFreeWaterVolume.
        /// </summary>
        public static string PhdTagFreeWaterVolume {
            get {
                return ResourceManager.GetString("PhdTagFreeWaterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagGrossObservableVolume.
        /// </summary>
        public static string PhdTagGrossObservableVolume {
            get {
                return ResourceManager.GetString("PhdTagGrossObservableVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagGrossStandardVolume.
        /// </summary>
        public static string PhdTagGrossStandardVolume {
            get {
                return ResourceManager.GetString("PhdTagGrossStandardVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagLiquidLevel.
        /// </summary>
        public static string PhdTagLiquidLevel {
            get {
                return ResourceManager.GetString("PhdTagLiquidLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagMaxVolume.
        /// </summary>
        public static string PhdTagMaxVolume {
            get {
                return ResourceManager.GetString("PhdTagMaxVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagNetStandardVolume.
        /// </summary>
        public static string PhdTagNetStandardVolume {
            get {
                return ResourceManager.GetString("PhdTagNetStandardVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagObservableDensity.
        /// </summary>
        public static string PhdTagObservableDensity {
            get {
                return ResourceManager.GetString("PhdTagObservableDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagProductId.
        /// </summary>
        public static string PhdTagProductId {
            get {
                return ResourceManager.GetString("PhdTagProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagProductLevel.
        /// </summary>
        public static string PhdTagProductLevel {
            get {
                return ResourceManager.GetString("PhdTagProductLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagProductName.
        /// </summary>
        public static string PhdTagProductName {
            get {
                return ResourceManager.GetString("PhdTagProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagReferenceDensity.
        /// </summary>
        public static string PhdTagReferenceDensity {
            get {
                return ResourceManager.GetString("PhdTagReferenceDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagTotalObservableVolume.
        /// </summary>
        public static string PhdTagTotalObservableVolume {
            get {
                return ResourceManager.GetString("PhdTagTotalObservableVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagWeightInAir.
        /// </summary>
        public static string PhdTagWeightInAir {
            get {
                return ResourceManager.GetString("PhdTagWeightInAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhdTagWeightInVacuum.
        /// </summary>
        public static string PhdTagWeightInVacuum {
            get {
                return ResourceManager.GetString("PhdTagWeightInVacuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe Expedition&lt;br/&gt;[ton].
        /// </summary>
        public static string PipeQuantity {
            get {
                return ResourceManager.GetString("PipeQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string Plant {
            get {
                return ResourceManager.GetString("Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plants.
        /// </summary>
        public static string Plants {
            get {
                return ResourceManager.GetString("Plants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreviousShiftTag.
        /// </summary>
        public static string PreviousShiftTag {
            get {
                return ResourceManager.GetString("PreviousShiftTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Unit.
        /// </summary>
        public static string ProcessUnit {
            get {
                return ResourceManager.GetString("ProcessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessUnit.
        /// </summary>
        public static string ProcessUnit1 {
            get {
                return ResourceManager.GetString("ProcessUnit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Unit Name.
        /// </summary>
        public static string ProcessUnitName {
            get {
                return ResourceManager.GetString("ProcessUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Units.
        /// </summary>
        public static string ProcessUnits {
            get {
                return ResourceManager.GetString("ProcessUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product1 {
            get {
                return ResourceManager.GetString("Product1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionPlanConfig.
        /// </summary>
        public static string ProductionPlanConfig {
            get {
                return ResourceManager.GetString("ProductionPlanConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productions.
        /// </summary>
        public static string Productions {
            get {
                return ResourceManager.GetString("Productions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Shift.
        /// </summary>
        public static string ProductionShift {
            get {
                return ResourceManager.GetString("ProductionShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionShift.
        /// </summary>
        public static string ProductionShift1 {
            get {
                return ResourceManager.GetString("ProductionShift1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Level.
        /// </summary>
        public static string ProductLevel {
            get {
                return ResourceManager.GetString("ProductLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLevelHighExtreme.
        /// </summary>
        public static string ProductLevelHighExtreme {
            get {
                return ResourceManager.GetString("ProductLevelHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLevelLowExtreme.
        /// </summary>
        public static string ProductLevelLowExtreme {
            get {
                return ResourceManager.GetString("ProductLevelLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductType.
        /// </summary>
        public static string ProductType1 {
            get {
                return ResourceManager.GetString("ProductType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductTypes.
        /// </summary>
        public static string ProductTypes {
            get {
                return ResourceManager.GetString("ProductTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityFactFormula.
        /// </summary>
        public static string QuantityFactFormula {
            get {
                return ResourceManager.GetString("QuantityFactFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityFactMembers.
        /// </summary>
        public static string QuantityFactMembers {
            get {
                return ResourceManager.GetString("QuantityFactMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Plan Formula.
        /// </summary>
        public static string QuantityPlanFormula {
            get {
                return ResourceManager.GetString("QuantityPlanFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityPlanMembers.
        /// </summary>
        public static string QuantityPlanMembers {
            get {
                return ResourceManager.GetString("QuantityPlanMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Offset.
        /// </summary>
        public static string ReadOffset {
            get {
                return ResourceManager.GetString("ReadOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Poll Time Slot.
        /// </summary>
        public static string ReadPollTimeSlot {
            get {
                return ResourceManager.GetString("ReadPollTimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Timestamp.
        /// </summary>
        public static string RecordTimestamp {
            get {
                return ResourceManager.GetString("RecordTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Density.
        /// </summary>
        public static string ReferenceDensity {
            get {
                return ResourceManager.GetString("ReferenceDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceDensityHighExtreme.
        /// </summary>
        public static string ReferenceDensityHighExtreme {
            get {
                return ResourceManager.GetString("ReferenceDensityHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceDensityLowExtreme.
        /// </summary>
        public static string ReferenceDensityLowExtreme {
            get {
                return ResourceManager.GetString("ReferenceDensityLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Administration.
        /// </summary>
        public static string RolesAdministration {
            get {
                return ResourceManager.GetString("RolesAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Expedition&lt;br/&gt;[ton].
        /// </summary>
        public static string SeaQuantity {
            get {
                return ResourceManager.GetString("SeaQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Product Type.
        /// </summary>
        public static string ShiftProductType {
            get {
                return ResourceManager.GetString("ShiftProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftProductType.
        /// </summary>
        public static string ShiftProductType1 {
            get {
                return ResourceManager.GetString("ShiftProductType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftProductTypes.
        /// </summary>
        public static string ShiftProductTypes {
            get {
                return ResourceManager.GetString("ShiftProductTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts Data.
        /// </summary>
        public static string ShiftsData {
            get {
                return ResourceManager.GetString("ShiftsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Slect Roles....
        /// </summary>
        public static string SlectRoles {
            get {
                return ResourceManager.GetString("SlectRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TankConfig.
        /// </summary>
        public static string TankConfig {
            get {
                return ResourceManager.GetString("TankConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TankMaster Code.
        /// </summary>
        public static string TankMasterCode {
            get {
                return ResourceManager.GetString("TankMasterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TankMasterProduct.
        /// </summary>
        public static string TankMasterProduct {
            get {
                return ResourceManager.GetString("TankMasterProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Name.
        /// </summary>
        public static string TankName {
            get {
                return ResourceManager.GetString("TankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanks Data.
        /// </summary>
        public static string TanksData {
            get {
                return ResourceManager.GetString("TanksData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        public static string TanksDateSelector {
            get {
                return ResourceManager.GetString("TanksDateSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Park.
        /// </summary>
        public static string TanksParkSelector {
            get {
                return ResourceManager.GetString("TanksParkSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Shift.
        /// </summary>
        public static string TanksShiftMinutesOffsetSelector {
            get {
                return ResourceManager.GetString("TanksShiftMinutesOffsetSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalObservableVolumeHighExtreme.
        /// </summary>
        public static string TotalObservableVolumeHighExtreme {
            get {
                return ResourceManager.GetString("TotalObservableVolumeHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalObservableVolumeLowExtreme.
        /// </summary>
        public static string TotalObservableVolumeLowExtreme {
            get {
                return ResourceManager.GetString("TotalObservableVolumeLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expediotion&lt;br/&gt;[ton].
        /// </summary>
        public static string TotalQuantity {
            get {
                return ResourceManager.GetString("TotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportType.
        /// </summary>
        public static string TransportType {
            get {
                return ResourceManager.GetString("TransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitConfig.
        /// </summary>
        public static string UnitConfig {
            get {
                return ResourceManager.GetString("UnitConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitsConfigs.
        /// </summary>
        public static string UnitsConfigs {
            get {
                return ResourceManager.GetString("UnitsConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitsDailyConfig.
        /// </summary>
        public static string UnitsDailyConfig {
            get {
                return ResourceManager.GetString("UnitsDailyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitsDailyConfigs.
        /// </summary>
        public static string UnitsDailyConfigs {
            get {
                return ResourceManager.GetString("UnitsDailyConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Daily Data.
        /// </summary>
        public static string UnitsDailyData {
            get {
                return ResourceManager.GetString("UnitsDailyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Data.
        /// </summary>
        public static string UnitsData {
            get {
                return ResourceManager.GetString("UnitsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        public static string UnitsDateSelector {
            get {
                return ResourceManager.GetString("UnitsDateSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Unit.
        /// </summary>
        public static string UnitsProcessUnitSelector {
            get {
                return ResourceManager.GetString("UnitsProcessUnitSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Shift.
        /// </summary>
        public static string UnitsProcessUnitShiftSelector {
            get {
                return ResourceManager.GetString("UnitsProcessUnitShiftSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnusableResidueLevel.
        /// </summary>
        public static string UnusableResidueLevel {
            get {
                return ResourceManager.GetString("UnusableResidueLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Administration.
        /// </summary>
        public static string UsersAdministration {
            get {
                return ResourceManager.GetString("UsersAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight In Air.
        /// </summary>
        public static string WeightInAir {
            get {
                return ResourceManager.GetString("WeightInAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightInAirHighExtreme.
        /// </summary>
        public static string WeightInAirHighExtreme {
            get {
                return ResourceManager.GetString("WeightInAirHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightInAirLowExtreme.
        /// </summary>
        public static string WeightInAirLowExtreme {
            get {
                return ResourceManager.GetString("WeightInAirLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight In Vacuum.
        /// </summary>
        public static string WeightInVacuum {
            get {
                return ResourceManager.GetString("WeightInVacuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightInVacuumHighExtreme.
        /// </summary>
        public static string WeightInVacuumHighExtreme {
            get {
                return ResourceManager.GetString("WeightInVacuumHighExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightInVacuumLowExtreme.
        /// </summary>
        public static string WeightInVacuumLowExtreme {
            get {
                return ResourceManager.GetString("WeightInVacuumLowExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
    }
}
